#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: orb
  labels:
    group: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orb
      group: core
  template:
    metadata:
      labels:
        app: orb
        group: core
    spec:
      containers:
        - name: orb
          envFrom:
            - configMapRef:
                name: orb-env
            - secretRef:
                name: orb-env-secret
          image: orb:latest
          args: ["start"]
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http-port
            - containerPort: 8091
              protocol: TCP
              name: prometheus
          livenessProbe:
            httpGet:
              path: /.well-known/nodeinfo
              port: http-port
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 5
