#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: svceng
kind: SedB64Transformer
metadata:
  name: sedb64transformer
argsOneLiner: s^||CORE_MONGODB_DSN||^${CORE_MONGODB_DSN}^ s^||CHS_REQUEST_TOKENS||^${CHS_REQUEST_TOKENS}^
