
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: trillian-log-signer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillian-log-signer
  template:
    metadata:
      labels:
        app: trillian-log-signer
    spec:
      containers:
        - name: trillian-log-signer
          args: [
              "--quota_system=noop",
              "--storage_system=postgres",
              "--pg_conn_str=$(POSTGRES_URI)",
              "--http_endpoint=$(HTTP_ENDPOINT)",
              "--force_master=true",
              "--logtostderr"
          ]
          envFrom:
            - configMapRef:
                name: trillian-log-signer-env
            - secretRef:
                name: trillian-log-signer-env-secret
          image: trillian-log-signer:latest
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http-port
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: trillian-log-signer
  labels:
    app: trillian-log-signer
spec:
  ports:
    - name: prometheus
      port: 9100
      protocol: TCP
      targetPort: http-port
  selector:
    app: trillian-log-signer
status:
  loadBalancer: {}
